{
    "data_folder_path": "data/CVE-2022-23531",
    "pull_requests_urls": [
        "https://github.com/DataDog/guarddog/pull/89/commits/a56aff58264cb6b7855d71b00dc10c39a5dbd306"
    ],
    "cve_name": "CVE-2022-23531",
    "repo": "DataDog/guarddog",
    "warnings": {
        "cve": "CVE-2022-23531",
        "warnings": []
    },
    "files_extension_stats": {
        ".lock": 1,
        ".toml": 1,
        ".txt": 1,
        ".py": 1
    },
    "file_number": 4,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 377,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}