{
    "data_folder_path": "data/CVE-2019-20907",
    "pull_requests_urls": [
        "https://github.com/python/cpython/pull/21454"
    ],
    "cve_name": "CVE-2019-20907",
    "repo": "python/cpython",
    "warnings": {
        "cve": "CVE-2019-20907",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Lib/test/recursion.tar",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NO_PATCH",
                "file_name": "Lib/test/recursion.tar",
                "message": "File has no patch data.\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Library/2020-07-12-22-16-58.bpo-39017.x3Cg-9.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 2,
        ".rst": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 10,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}