{
    "data_folder_path": "data/CVE-2023-49797",
    "pull_requests_urls": [
        "https://github.com/pyinstaller/pyinstaller/pull/7827"
    ],
    "cve_name": "CVE-2023-49797",
    "repo": "pyinstaller/pyinstaller",
    "warnings": {
        "cve": "CVE-2023-49797",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "PyInstaller/fake-modules/_pyi_rth_utils/__init__.py",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "PyInstaller/fake-modules/_pyi_rth_utils/_win32.py",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "PyInstaller/hooks/pre_find_module_path/hook-_pyi_rth_utils.py",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "news/7827.bugfix.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".cfg": 1,
        ".py": 6,
        ".in": 1,
        ".rst": 1
    },
    "file_number": 9,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 368,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}