{
    "data_folder_path": "data/CVE-2019-9948",
    "pull_requests_urls": [
        "https://github.com/python/cpython/pull/11842"
    ],
    "cve_name": "CVE-2019-9948",
    "repo": "python/cpython",
    "warnings": {
        "cve": "CVE-2019-9948",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Library/2019-02-13-17-21-10.bpo-35907.ckk2zg.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 2,
        ".rst": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 12,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}