{
    "data_folder_path": "data/CVE-2018-12291",
    "pull_requests_urls": [
        "https://github.com/matrix-org/synapse/pull/3371"
    ],
    "cve_name": "CVE-2018-12291",
    "repo": "matrix-org/synapse",
    "warnings": {
        "cve": "CVE-2018-12291",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 4,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}