{
    "data_folder_path": "data/CVE-2021-41195",
    "pull_requests_urls": [
        "https://github.com/tensorflow/tensorflow/pull/51733"
    ],
    "cve_name": "CVE-2021-41195",
    "repo": "tensorflow/tensorflow",
    "warnings": {
        "cve": "CVE-2021-41195",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 1,
        ".h": 1
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 18,
    "private_key_files": [],
    "languages": [
        "C",
        "Python"
    ]
}