{
    "data_folder_path": "data/CVE-2021-3733",
    "pull_requests_urls": [
        "https://github.com/python/cpython/pull/24391"
    ],
    "cve_name": "CVE-2021-3733",
    "repo": "python/cpython",
    "warnings": {
        "cve": "CVE-2021-3733",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Security/2021-01-31-05-28-14.bpo-43075.DoAXqO.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 1,
        ".rst": 1
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 3,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}