{
    "data_folder_path": "data/CVE-2022-26184",
    "pull_requests_urls": [
        "https://github.com/python-poetry/poetry-core/pull/205/commits/fa9cb6f358ae840885c700f954317f34838caba7"
    ],
    "cve_name": "CVE-2022-26184",
    "repo": "python-poetry/poetry-core",
    "warnings": {
        "cve": "CVE-2022-26184",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 94,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}