{
    "data_folder_path": "data/CVE-2021-28957",
    "pull_requests_urls": [
        "https://github.com/lxml/lxml/pull/316/commits/10ec1b4e9f93713513a3264ed6158af22492f270"
    ],
    "cve_name": "CVE-2021-28957",
    "repo": "lxml/lxml",
    "warnings": {
        "cve": "CVE-2021-28957",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 17,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}