{
    "data_folder_path": "data/CVE-2021-3177",
    "pull_requests_urls": [
        "https://github.com/python/cpython/pull/24239"
    ],
    "cve_name": "CVE-2021-3177",
    "repo": "python/cpython",
    "warnings": {
        "cve": "CVE-2021-3177",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Security/2021-01-18-09-27-31.bpo-42938.4Zn4Mp.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 1,
        ".rst": 1,
        ".c": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 96,
    "private_key_files": [],
    "languages": [
        "C",
        "Python"
    ]
}