{
    "data_folder_path": "data/CVE-2020-28493",
    "pull_requests_urls": [
        "https://github.com/pallets/jinja/pull/1343"
    ],
    "cve_name": "CVE-2020-28493",
    "repo": "pallets/jinja",
    "warnings": {
        "cve": "CVE-2020-28493",
        "warnings": []
    },
    "files_extension_stats": {
        ".rst": 1,
        ".py": 1
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 117,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}